name: anubis
version: git
summary: Anubis
description: |
  Subdomain enumeration and information gathering tool

grade: devel
confinement: devmode

apps:
  anubis:
    command: anubis

parts:
  anubis:
    plugin: python
    python-version: python3
    source: .